# Generated by Django 5.2.15 on 2026-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='avatar URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_buddy',
            field=models.BooleanField(default=False, verbose_name='is buddy'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='push token'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20, verbose_name='verification status'),
        ),
    ]
