# Generated by Django 4.2.19 on 2025-03-04 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(default=18, verbose_name="minimum age"),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        default=100, verbose_name="maximum age"
                    ),
                ),
                (
                    "preferred_genders",
                    models.JSONField(default=list, verbose_name="preferred genders"),
                ),
                (
                    "interest_importance",
                    models.FloatField(
                        default=0.5,
                        help_text="Weight from 0 to 1, where 1 is most important",
                        verbose_name="interest importance weight",
                    ),
                ),
                (
                    "distance_importance",
                    models.FloatField(
                        default=0.3,
                        help_text="Weight from 0 to 1, where 1 is most important",
                        verbose_name="distance importance weight",
                    ),
                ),
                (
                    "availability_importance",
                    models.FloatField(
                        default=0.2,
                        help_text="Weight from 0 to 1, where 1 is most important",
                        verbose_name="availability importance weight",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="matched at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiration date"
                    ),
                ),
                (
                    "interests_similarity_score",
                    models.FloatField(
                        default=0.0, verbose_name="interests similarity score"
                    ),
                ),
                (
                    "distance_score",
                    models.FloatField(default=0.0, verbose_name="distance score"),
                ),
                (
                    "availability_score",
                    models.FloatField(default=0.0, verbose_name="availability score"),
                ),
                (
                    "total_match_score",
                    models.FloatField(default=0.0, verbose_name="total match score"),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "matches",
                "unique_together": {("initiator", "responder")},
            },
        ),
    ]
