name: GetMeBuddy Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'GetMeBuddyApp/**'
      - '.github/workflows/frontend-ci-cd.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'GetMeBuddyApp/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: GetMeBuddyApp/package-lock.json
    
    - name: Install dependencies
      run: |
        cd GetMeBuddyApp
        npm ci
    
    - name: Lint code
      run: |
        cd GetMeBuddyApp
        npm run lint
    
    - name: Run tests
      run: |
        cd GetMeBuddyApp
        npm test
    
  build-android:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: GetMeBuddyApp/package-lock.json
    
    - name: Install dependencies
      run: |
        cd GetMeBuddyApp
        npm ci
    
    - name: Build Android release
      run: |
        cd GetMeBuddyApp/android
        ./gradlew assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: GetMeBuddyApp/android/app/build/outputs/apk/release/app-release.apk
    
  build-ios:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: GetMeBuddyApp/package-lock.json
    
    - name: Install dependencies
      run: |
        cd GetMeBuddyApp
        npm ci
    
    - name: Install iOS dependencies
      run: |
        cd GetMeBuddyApp/ios
        pod install
    
    - name: Build iOS
      run: |
        cd GetMeBuddyApp
        xcodebuild -workspace ios/GetMeBuddyApp.xcworkspace -scheme GetMeBuddyApp -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build